### ISSUE TITLE
[Multilingual] Chinese support (or multi-langual)

### ISSUE THREAD

**Issue by MonolithFoundation** [KAIST-AILab/SyncVSR#2]
Maybe many language are hard or even not possiable, but English and Mandrain support could be far more useable in VSR field.

Do u have any thoughts on this

**Comment by snoop2head** [comment]
@MonolithFoundation 
I think Chinese language is inherently more difficult for VSR due to the prevalence of homophenes of the existence stemmed from 拼音 (pinyin).

Currently, my server devices that were used to train VSR models were taken away (about 6 months ago). For now, I can't train the any other models, but if there's a chance to access any Chinese dataset with hardware devices, I may support it.
