### ISSUE TITLE
[Multilingual] Chinese dataset model

### ISSUE THREAD

**Issue by Liajun** [KAIST-AILab/SyncVSR#22]
"Hello, author. I would like to inquire if the model weights for LRW-1000 in Chinese can be uploaded?

**Comment by snoop2head** [comment]
@Liajun 
As mentioned in the https://github.com/KAIST-AILab/SyncVSR/issues/1#issuecomment-2344956180, we are planning not to release the Chinese VSR model due to issues with video and audio drifting out of sync, raising concerns about its reliability on out-of-domain dataset, despite its solid benchmark performance. I recommend to train your own custom model on LRW-1000 or on [CN-CVS series](https://cnceleb.org/) on the [CNVSRC series](https://cnceleb.org/competition). Please refer to 
https://github.com/KAIST-AILab/SyncVSR/issues/10#issuecomment-2406727221 for additional details or refer to `[Multilingual]` headers in closed issues.

**Comment by Liajun** [comment]
Thank you！
